services:
  app:
    image: my_java17_app
    container_name: my_java_app
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    networks:
      - mynetwork
    depends_on:
      - dbmariadb

  dbmariadb:
    image: mariadb:10.4.32
    container_name: mariadb_database
    environment:
      MYSQL_ROOT_PASSWORD: gte
      MYSQL_DATABASE: gpro
      MYSQL_PASSWORD: gte
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mariadb_data:
  src:
  target:

networks:
  mynetwork:
    driver: bridge
